repositories{
    maven {
        // JEI
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
}

dependencies {
    implementation "curse.maven:firmalife-453394:8364676"
    implementation "curse.maven:jade-324717:7545219"
    compileOnly "curse.maven:jei-238222:7420587"
    runtimeOnly "curse.maven:jei-238222:7420587"
}
